title: Olabode Shonibare
logo: https://media.licdn.com/dms/image/v2/D4D03AQHWMf9VomO3vg/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1722325093890?e=1730937600&v=beta&t=IVm63KZFq1cDT4k3K9S773fF9BCTrftwA7zyvTzXW8s
#subscription: "text below image" # Text to display below the logo
show_downloads: true 
theme: jekyll-theme-minimal
