# Basic Settings
title: Olabode Shonibare
logo: "https://media.licdn.com/dms/image/D4D35AQGQUczKM_wA_Q/profile-framedphoto-shrink_200_200/0/1701705313883?e=1716663600&v=beta&t=2ZthwE_xh8yQ-1mofpTf-BcOMi_hrE69ovZTtM5d6nQ"
subscription: text below image
description: 
baseurl: "https://bit.ly/3Xp9AAt" # The subpath of your site (e.g., /my-site)
url: "https://olabode3262.github.io" # Your base URL

# Author Information
author:
  name: "Olabode Shonibare"
  email: "olabode.shonibare@gmail.com"

# Theme Settings
theme: jekyll-minima # The theme for your Jekyll site

# Social Links (used by some themes)
social_links:
  twitter: "https://twitter.com/slowburne"
  github: "https://github.com/olabode3262"

# Defaults for posts or pages
defaults:
  - scope:
      path: "" # empty string means all files
    values:
      layout: "post"
      author: "Olabode Shonibare"

