title: Olabode Shonibare
logo: https://media.licdn.com/dms/image/D4D35AQGQUczKM_wA_Q/profile-framedphoto-shrink_200_200/0/1701705313883?e=1716663600&v=beta&t=2ZthwE_xh8yQ-1mofpTf-BcOMi_hrE69ovZTtM5d6nQ
subscription: text below image
show_downloads: true
theme: jekyll-theme-minimal
